---
- hosts: all
  user:  root
  roles:
    - basic
    - apt
    - zsh
    - dotfiles
    - vim
    - ssh
    - direnv
    - ntp
    - swap_file
    - imagemagick
    - ruby
    - nodejs
    - mysql
    - postgresql
    - redis
    - heroku
    - peco
